specVersion: 0.2.0
name: astar-stats-indexer
version: 0.0.1
description: Astar statistics indexer
repository: 'https://github.com/subquery/astar-subql-starters'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://rpc.astar.network'
  genesisHash: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewStakingEraEvent
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: NewDappStakingEra
        - handler: handleBlock
          kind: substrate/BlockHandler
